<!DOCTYPE html>
{{-- Start HTML structure --}}
<html>
<head>
    {{-- Set UTF-8 charset meta tag --}}
    <meta charset="utf-8">
    {{-- Title of the PDF document --}}
    <title>Resort Analytics Report</title>
    {{-- CSS styling block optimized for PDF rendering --}}
    <style>
        /* Base page font family selection */
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; line-height: 1.4; font-size: 12px; }
        /* Page margins configuration */
        @page { margin: 40px; }
        /* Main heading title styling with ocean color theme */
        .header { text-align: center; border-bottom: 2px solid #0ea5e9; padding-bottom: 10px; margin-bottom: 20px; }
        /* Title text layout */
        .title { font-size: 24px; font-weight: bold; color: #0c4a6e; margin: 0; }
        /* Subtitle layout styling */
        .subtitle { font-size: 12px; color: #64748b; margin-top: 5px; }
        /* Standard section wrapper formatting */
        .section { margin-bottom: 25px; page-break-inside: avoid; }
        /* Section heading layout */
        .section-title { font-size: 16px; font-weight: bold; color: #164e63; border-bottom: 1px solid #e2e8f0; padding-bottom: 5px; margin-bottom: 10px; }
        /* Report metadata details block grid */
        .meta-grid { width: 100%; margin-bottom: 20px; border-collapse: collapse; }
        /* Data grid table cell padding */
        .meta-grid td { padding: 4px 0; font-size: 11px; }
        /* Standard data display tables formatting */
        .data-table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        /* Table headers styling matching resort branding colors */
        .data-table th { background-color: #0ea5e9; color: white; text-align: left; padding: 8px; font-size: 11px; text-transform: uppercase; }
        /* Table data rows padding and border separations */
        .data-table td { padding: 8px; border-bottom: 1px solid #e2e8f0; font-size: 11px; }
        /* Alternating row background shading */
        .data-table tr:nth-child(even) { background-color: #f8fafc; }
        /* Numeric align right utility */
        .text-right { text-align: right; }
        /* Bold total text highlights styling */
        .text-bold { font-weight: bold; }
        /* Numeric grid layouts */
        .summary-box { background-color: #f0f9ff; border: 1px solid #bae6fd; padding: 12px; rounded: 8px; margin-bottom: 15px; }
        /* Bullet point alignments */
        .summary-title { font-size: 13px; font-weight: bold; color: #0369a1; margin-bottom: 5px; }
    </style>
</head>
<body>

    {{-- Main Document Header block --}}
    <div class="header">
        <h1 class="title">Talisay Beach Resort</h1>
        <div class="subtitle">System Analytics & Business Intelligence Report</div>
    </div>

    {{-- Metadata grid section details --}}
    <table class="meta-grid">
        <tr>
            <td><strong>Report Type:</strong> Comprehensive Analytics Summary</td>
            <td class="text-right"><strong>Generated On:</strong> {{ now()->format('F d, Y h:i A') }}</td>
        </tr>
        <tr>
            <td><strong>Resort Location:</strong> Barangay Maslug, Baybay City, Leyte</td>
            <td class="text-right"><strong>Generated By:</strong> {{ auth()->user()->name }}</td>
        </tr>
    </table>

    {{-- Financial summary block --}}
    <div class="section">
        <div class="section-title">1. Financial Revenue Performance</div>
        <div class="summary-box">
            <div class="summary-title">Total Revenue Metrics</div>
            <div>Accumulated Revenue: <strong>PHP {{ number_format($totalRevenue, 2) }}</strong></div>
            <div>Awaiting Clearances: <strong>PHP {{ number_format($pendingAmount, 2) }}</strong></div>
            <div>Total Refunded Claims: <strong>PHP {{ number_format($refundedAmount, 2) }}</strong></div>
        </div>

        <table class="data-table">
            <thead>
                <tr>
                    <th>Month Identifier</th>
                    <th class="text-right">Gross Total Amount (PHP)</th>
                </tr>
            </thead>
            <tbody>
                @foreach($monthlyRevenue as $item)
                <tr>
                    <td>{{ $item->month }}</td>
                    <td class="text-right">{{ number_format($item->total, 2) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    {{-- Occupancy rates data section --}}
    <div class="section">
        <div class="section-title">2. Daily Resort Occupancy Statistics</div>
        <div class="summary-box">
            <div>Median Daily Occupancy Utilization Rate: <strong>{{ $averageOccupancy }}%</strong></div>
        </div>

        <table class="data-table">
            <thead>
                <tr>
                    <th>Visit Date</th>
                    <th>Booked Guests</th>
                    <th>Maximum Daily Cap</th>
                    <th class="text-right">Daily Utilization Rate</th>
                </tr>
            </thead>
            <tbody>
                @foreach($dailyOccupancy as $day)
                <tr>
                    <td>{{ $day['date'] }}</td>
                    <td>{{ $day['current_count'] }} guests</td>
                    <td>{{ $day['max_capacity'] }} slots</td>
                    <td class="text-right">{{ $day['utilization'] }}%</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    {{-- Popular package metrics section --}}
    <div class="section">
        <div class="section-title">3. Popular Service Packages</div>
        <table class="data-table">
            <thead>
                <tr>
                    <th>Resort Package Name</th>
                    <th>Package Price Rate</th>
                    <th>Max Guests Capacity</th>
                    <th class="text-right">Confirmed Bookings Count</th>
                </tr>
            </thead>
            <tbody>
                @foreach($popularPackages as $pkg)
                <tr>
                    <td>{{ $pkg->name }}</td>
                    <td>PHP {{ number_format($pkg->price, 2) }}</td>
                    <td>{{ $pkg->max_capacity }} guests</td>
                    <td class="text-right">{{ $pkg->bookings_count }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    {{-- Guest review satisfaction metrics --}}
    <div class="section">
        <div class="section-title">4. Guest Satisfaction Sentiment Metrics</div>
        <div class="summary-box">
            <div>Average Review Rating Score: <strong>{{ $averageRating }} / 5.0 Stars</strong></div>
            <div>Total Moderated Reviews: <strong>{{ $totalReviews }} reviews</strong></div>
        </div>
    </div>

</body>
</html>
